[platformio]
src_dir = firmware/FlockNoir

[env:xiao_esp32s3_sense]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
build_flags = -DBOARD_HAS_PSRAM -DARDUINO_USB_CDC_ON_BOOT=1 -DARDUINO_USB_MODE=1
lib_deps = mikalhart/TinyGPSPlus@1.0.3
monitor_speed = 115200
