#!/usr/bin/env python3
"""
logo2header.py  -  embed the UNALTERED brand logo into the firmware.

Reads  assets/logo.(png|jpg|jpeg|gif|webp)  and writes  logo.h  as a PROGMEM
byte array that the web server serves verbatim at /logo.png. The image bytes
are copied exactly -- no resize, recolor, or re-encode.

Usage:
    python tools/logo2header.py                 # auto-find assets/logo.*
    python tools/logo2header.py path/to/logo.png
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

MIME = {
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".gif": "image/gif", ".webp": "image/webp", ".svg": "image/svg+xml",
}


def find_logo():
    assets = os.path.join(ROOT, "assets")
    if not os.path.isdir(assets):
        return None
    for ext in (".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"):
        p = os.path.join(assets, "logo" + ext)
        if os.path.isfile(p):
            return p
    return None


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else find_logo()
    if not src or not os.path.isfile(src):
        print("ERROR: no logo found. Save your file as assets/logo.png "
              "(or pass a path).")
        sys.exit(1)

    ext = os.path.splitext(src)[1].lower()
    mime = MIME.get(ext, "image/png")
    data = open(src, "rb").read()

    out = os.path.join(ROOT, "logo.h")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/logo2header.py -- do not hand edit\n")
        f.write("// Source: %s (%d bytes) -- embedded UNALTERED\n" %
                (os.path.basename(src), len(data)))
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write("static const uint8_t LOGO_PNG[] PROGMEM = {\n")
        for i, b in enumerate(data):
            f.write("0x%02x," % b)
            if (i + 1) % 16 == 0:
                f.write("\n")
        f.write("\n};\n")
        f.write("static const size_t LOGO_PNG_LEN = %d;\n" % len(data))
        f.write('static const char  *LOGO_MIME = "%s";\n' % mime)

    print("Wrote %s  (%d bytes embedded, mime=%s)" % (out, len(data), mime))
    if len(data) > 180_000:
        print("NOTE: %d bytes is large for flash embedding. Consider serving "
              "from the SD card instead (copy logo.png to the card root)." % len(data))


if __name__ == "__main__":
    main()
